services:
  postgres:
    image: postgres:17
    container_name: postgres-service
    environment:
      POSTGRES_USER: wikorna
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: FactoryDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wikorna"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
